import { resolve } from 'node:path'
import {
  fileURLToPath, URL
} from 'node:url'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify'

const minifyJS = process.env.BUILD_MINIFY_JS ?? true

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({ template: { transformAssetUrls } }),
    vuetify()
  ],
  esbuild: {
    minify: Boolean(minifyJS),
    minifySyntax: Boolean(minifyJS)
  },
  build: {
    cssCodeSplit: false,
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'wysiwyg',
      formats: ['es'], // adding 'umd' requires globals set to every external module,
      fileName: (format) => `wysiwyg.${format}.js`
    },
    rollupOptions: {
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: 'named'
      }
    },
    emptyOutDir: false // to retain the types folder generated by tsc
  },
  resolve: { alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) } }
})
